# Generated by Django 4.0.3 on 2022-07-29 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='backend\\static\\image\\default-image.jpg', null=True, upload_to=''),
        ),
    ]
